AllCops:
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Max: 120 # Default: 80

Metrics/MethodLength:
  Max: 20 # Default: 10

Naming/AccessorMethodName: # TODO: Enable and fix API at some point.
  Enabled: false

Style/Documentation:
  # This cop checks for missing top-level documentation of classes and modules.
  # Classes with no body and namespace modules are exempt from the check.
  # Namespace modules are modules that have nothing in their bodies except
  # classes or other modules.
  Enabled: false
